In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

X=dataset.iloc[:,:4].values
y = dataset['species'].values
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [3]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2)

In [4]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [6]:
y_pred = classifier.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix 
cm =confusion_matrix(y_test, y_pred) 
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test,y_pred))
print(cm)

Accuracy :  0.9333333333333333
[[14  0  0]
 [ 0  6  1]
 [ 0  1  8]]


In [8]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

   Real Values Predicted Values
0       setosa           setosa
1   versicolor       versicolor
2       setosa           setosa
3    virginica        virginica
4   versicolor        virginica
5    virginica        virginica
6   versicolor       versicolor
7       setosa           setosa
8       setosa           setosa
9    virginica        virginica
10  versicolor       versicolor
11  versicolor       versicolor
12   virginica        virginica
13   virginica        virginica
14      setosa           setosa
15   virginica        virginica
16      setosa           setosa
17   virginica        virginica
18      setosa           setosa
19   virginica        virginica
20      setosa           setosa
21      setosa           setosa
22      setosa           setosa
23   virginica       versicolor
24      setosa           setosa
25      setosa           setosa
26  versicolor       versicolor
27  versicolor       versicolor
28      setosa           setosa
29      setosa           setosa


In [9]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [10]:
m=accuracy_score(y_test, y_pred)
print("error rate:-",1-m)

error rate:- 0.06666666666666665


In [11]:
print('Precision:',precision_score(y_test,y_pred,average='micro'))

Precision: 0.9333333333333333


In [12]:
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

Recall Score: 0.9333333333333333
